### ISSUE TITLE
Problem with self-closing tags

### ISSUE THREAD

**Issue by Sorokin-Anton** [holocron-hq/safe-mdx#1]
If I use self-closing tags like `<br />` in mdx source file I'm getting 

```
Error: br is a self-closing tag and must neither have `children` nor use `dangerouslySetInnerHTML`.
```

Probably, that's because parser creates `br` with an empty list of children, instead of not creating children at all

I invented a workaround but I need to specify each tag here

```
        <SafeMdxRenderer
          code={mdxContent}
          components={{
            br(_props: any) {
              return <br />;
            } ...
```

**Comment by remorses** [comment]
Can you post your mdx content?

**Comment by remorses** [comment]
Fixed in latest version
