### ISSUE TITLE
Syntax Highlighting

### ISSUE THREAD

**Issue by harveyjing** [holocron-hq/safe-mdx#14]
## Background
1. My app is running on Cloudflare Pages, and this library is perfect—thank you for your work!
2. I want to implement syntax highlighting using `react-syntax-highlighter`.
3. I noticed that there are popular solutions for syntax highlighting, such as `prismjs` and `highlight.js`.

## Question
In [this commit](https://github.com/holocron-hq/safe-mdx/commit/70df8c9acada7a674db2f914ef5fb9f34f68b380), I noticed that the `className` property was removed. Could you clarify the reasoning behind this change?

## Desired Outcome
I’m looking for guidance or a solution to include language-specific hints for syntax highlighting within this library.

**Comment by remorses** [comment]
I don’t remember anymore why this change was made, a PR is welcome to add back the class

also, for inline code there should be an inlineCode key instead of just code

**Comment by harveyjing** [comment]
Hi @remorses , I have raised a PR #15 , please review it. Thanks
