### ISSUE TITLE
Vulnerability: JavaScript Evaluation on Links and Sources

### ISSUE THREAD

**Issue by ChristianMurphy** [holocron-hq/safe-mdx#5]
### Disclosure

This vulnerability was privately disclosed to maintainers via email on February 14, 2024.
After a 60 day waiting period is being publicly disclosed.

### Context

To be secure, evaluation should not be allowed.
The project's stated goal is:

> Render MDX in React without eval

There are many possible ways scripts can be evaluated.
A few possible entry points are through link href evaluation and through source evaluation.
Projects like: https://github.com/remarkjs/react-markdown and https://github.com/syntax-tree/hast-util-sanitize add a sanitizer to ensure links and sources are safe.
`safe-mdx` does not currently, which allows insecure evaluation.

### Minimal reproducible examples

With `safe-mdx` version 0.0.4

Link example:

```ts
import { SafeMdxRenderer } from 'safe-mdx';

const code = `
[test](javascript:alert('evaluated'))
`;

export function App() {
  return <SafeMdxRenderer code={code} components={{}} />;
}
```

https://stackblitz.com/edit/vitejs-vite-dpy9or?file=src%2FApp.tsx

Source example:

```ts
import { SafeMdxRenderer } from 'safe-mdx';

const code = `
<iframe src="javascript:alert('evaluation')"></iframe>
`;

export function App() {
  return <SafeMdxRenderer code={code} components={{}} />;
}
```

https://stackblitz.com/edit/vitejs-vite-ff3dcr?file=src%2FApp.tsx

### Expected Result

No evaluation should happen and no alert should print.

### Actual Result

JavaScript is evaluated and an alert appears.

**Comment by remorses** [comment]
This code is evaluated on the client which is fine. This projects aims to not evaluate the code on the server.

**Comment by ChristianMurphy** [comment]
> This code is evaluated on the client which is fine

It is not "fine", untrusted code evaluation client side is a serious problem.

> This projects aims to not evaluate the code on the server.

That is not what the README of the project says.
It states it prevents evaluation broadly.

You are welcome to scope your project however you want.
Do not mislead adopters in the README.

**Comment by ChristianMurphy** [comment]
[c8076e2](https://github.com/holocron-hq/safe-mdx/commit/c8076e274c036390b55b3a0c5d5c9ccd642daefa) is a step in the right direction.
With a project name like `safe-mdx` I'd recommend having a dedicated security section in the readme.

Something like https://github.com/remarkjs/react-markdown?tab=readme-ov-file#security

For example

---

## Security

`safe-mdx` is designed to avoid server-side evaluation of untrusted Markdown input.

However, it's important to note that `safe-mdx` does not provide protection against client-side vulnerabilities, such as Cross-Site Scripting (XSS) or script injection attacks. While `safe-mdx` itself does not perform any evaluation or rendering of user-provided content, the rendering library or components used in conjunction with `safe-mdx` may introduce security risks if not properly configured or sanitized.

To enhance the security of your application when using `safe-mdx`, we recommend applying additional sanitization measures, such as the `rehype-sanitize` plugin. `rehype-sanitize` allows you to define a whitelist of allowed HTML elements, attributes, and protocols, effectively reducing the risk of XSS attacks by removing potentially malicious content from the rendered output.
