### ISSUE TITLE
Rehype-Sanitize Example

### ISSUE THREAD

**Issue by prests** [holocron-hq/safe-mdx#6]
Appreciate you creating a security focused mdx rendered. I'm struggling to figure out how to make rehype-sanitize work with your package. Could you provide a basic example?

**Comment by remorses** [comment]
What is the use case?

rehype-sanitize does not work with this package, that plugin is used in the rehype ast to html pass, this package skips it and instead renders jsx instead of rehype ast. That section on the readme was wrong, this is what is recommended for security purposes:

> This is ok if you render your MDX in isolation from each tenant, for example on different subdomains, this way an XSS attack cannot affect all tenants. If instead you render the MDX from different tenants on the same domain, one tenant could steal cookies set from other customers.

**Comment by remorses** [comment]
You could implement your own sanitizer on top of safe-mdx if you really want it (but i would avoid it, it gives a false sense of security)

This is how the sanitizer is implemented, by default it also removes classes from elements:
https://github.com/syntax-tree/hast-util-sanitize/blob/main/lib/schema.js
