### ISSUE TITLE
frontmatter example

### ISSUE THREAD

**Issue by dsmmcken** [holocron-hq/safe-mdx#9]
I see it's using [remark-frontmatter](https://github.com/holocron-hq/safe-mdx/blob/4844e98a7bb18e5819502d1c9916a0ead8ecbab1/src/safe-mdx.tsx#L17), but how do I actually get the data from it? A quick example in the readme would be appreciated thanks.

**Comment by remorses** [comment]
Added an example https://github.com/holocron-hq/safe-mdx/tree/main?tab=readme-ov-file#reading-the-frontmatter
